# Generated by Django 4.2 on 2025-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subscription_products_su_status_9619d3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('expired', 'EXPIRED'), ('canceled', 'CANCELED')], default='active', max_length=20),
        ),
    ]
