version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    env_file:
      - ./core/.env
    networks:
      - main
  
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - main

networks:
  main: