# Generated by Django 4.2 on 2025-05-30 16:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09129876543'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,11}$')]),
        ),
    ]
