# Generated by Django 4.2 on 2025-06-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
